name: acceso mv ssh

on:
  push:

jobs:
    prueba-ssh-workflow:
        runs-on:  ubuntu-latest
        steps:
            - name: clonar repo
              uses: actions/checkout@v6

            - name: conexion ssh
              run: |
                  ssh ${{ secrets.USER_NAME_MV }}@${{ secrets.USER_IP_MV }}
                  pwd
