name: hola primer workflow

on:
  push:

jobs:
  primer-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: hola echo
        run: echo "primer workflow"

      - name: clonar
        uses: actions//checkout@v6

      - name: dar permisos y ejecutamos
        run: |
            chmod +x hola.sh
            ./hola.sh

